import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Align",
  description: "Terms of Service for the Align relationship agreements app.",
};

const LAST_UPDATED = "February 2026";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-cream">
      {/* Header */}
      <header className="border-b border-border">
        <div className="mx-auto max-w-3xl px-6 py-5 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5 group">
            <div className="w-7 h-7 rounded-full bg-primary flex items-center justify-center transition-transform duration-300 group-hover:scale-110">
              <div className="w-2.5 h-2.5 rounded-full bg-cream" />
            </div>
            <span className="font-display text-lg font-semibold text-ink">
              Align
            </span>
          </Link>
          <Link
            href="/"
            className="text-sm text-ink-secondary hover:text-primary transition-colors"
          >
            &larr; Back to home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="mx-auto max-w-3xl px-6 py-12 lg:py-16">
        <h1 className="font-display text-3xl lg:text-4xl font-semibold text-ink mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-ink-tertiary mb-10">
          Last updated: {LAST_UPDATED}
        </p>

        <div className="space-y-8">
          <p className="text-ink-secondary leading-relaxed text-lg">
            By using Align, you agree to these terms. Please read them
            carefully.
          </p>

          <section>
            <h2 className="font-display text-xl font-semibold text-ink mb-3">
              1. What Align is (and isn&apos;t)
            </h2>
            <p className="text-ink-secondary leading-relaxed">
              Align is a tool that helps couples articulate and formalize
              relationship agreements. It is <strong>not</strong> a substitute
              for couples therapy, legal counsel, or professional mediation.
              Agreements created in Align are personal commitments between
              partners and are not legally binding contracts.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-ink mb-3">
              2. Your account
            </h2>
            <p className="text-ink-secondary leading-relaxed">
              You must provide a valid email address to create an account. You
              are responsible for maintaining the security of your account. We
              authenticate using email-based verification codes (no passwords
              to remember or lose).
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-ink mb-3">
              3. Content you create
            </h2>
            <p className="text-ink-secondary leading-relaxed">
              You retain ownership of all content you create within Align,
              including quiz answers, freetext responses, and agreement
              clauses. We do not claim any intellectual property rights over
              your content. We use your content only to provide the service
              (generating and storing your agreement).
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-ink mb-3">
              4. AI-generated content
            </h2>
            <p className="text-ink-secondary leading-relaxed">
              Agreement clauses are generated by AI based on your inputs. While
              we strive for high-quality, thoughtful output, AI-generated
              content may not always perfectly capture your intentions. You
              have full control to edit, accept, or reject any clause before
              signing.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-ink mb-3">
              5. Safety commitments
            </h2>
            <p className="text-ink-secondary leading-relaxed">
              Our AI is designed to never generate clauses that involve
              surveillance, tracking, isolation from support networks, or
              controlling behavior. If you encounter content that feels unsafe,
              please contact us immediately at{" "}
              <a
                href="mailto:support@tryalign.app"
                className="text-primary hover:underline"
              >
                support@tryalign.app
              </a>
              .
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-ink mb-3">
              6. Subscriptions and billing
            </h2>
            <p className="text-ink-secondary leading-relaxed">
              Align offers both free and premium tiers. Premium subscriptions
              are managed through the App Store or Google Play. Billing,
              renewals, and cancellations are handled by the respective
              platform. We do not directly process payment information.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-ink mb-3">
              7. Termination
            </h2>
            <p className="text-ink-secondary leading-relaxed">
              You may delete your account at any time. We may suspend or
              terminate accounts that violate these terms. Upon account
              deletion, your data will be permanently removed from our
              systems.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-ink mb-3">
              8. Limitation of liability
            </h2>
            <p className="text-ink-secondary leading-relaxed">
              Align is provided &ldquo;as is&rdquo; without warranties of any
              kind. We are not liable for any damages arising from your use of
              the service, including but not limited to relationship outcomes,
              data loss, or service interruptions.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-ink mb-3">
              9. Changes to these terms
            </h2>
            <p className="text-ink-secondary leading-relaxed">
              We may update these terms from time to time. We will notify you
              of significant changes through the app or via email. Continued
              use of Align after changes constitutes acceptance of the updated
              terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold text-ink mb-3">
              10. Contact
            </h2>
            <p className="text-ink-secondary leading-relaxed">
              Questions about these terms? Contact us at{" "}
              <a
                href="mailto:support@tryalign.app"
                className="text-primary hover:underline"
              >
                support@tryalign.app
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border mt-16">
        <div className="mx-auto max-w-3xl px-6 py-6 flex items-center justify-between text-xs text-ink-tertiary">
          <span>&copy; {new Date().getFullYear()} Align</span>
          <Link
            href="/privacy"
            className="hover:text-primary transition-colors"
          >
            Privacy Policy
          </Link>
        </div>
      </footer>
    </div>
  );
}
